Champs = {
	["Aatrox"] = {
		{spell_name = "AatroxQ", root_type = "linear"},
		{spell_name = "AatroxQ2", root_type = "linear"},
		{spell_name = "AatroxQ3", root_type = "linear"},
		{spell_name = "AatroxW", root_type = "circular"},
		{spell_name = "AatroxE", root_type = "circular"},
	},
	["Ahri"] = {
		{spell_name = "AhriR", root_type = "circular"},
		{spell_name = "AhriQ", root_type = "circular"},
		{spell_name = "AhriE", root_type = "circular"},
	},
	["Akali"] = {
		{spell_name = "AkaliRb", root_type = "circular"},
		{spell_name = "AkaliQ", root_type = "circular"},
		{spell_name = "AkaliQMis", root_type = "circular"},
		{spell_name = "AkaliQMis0", root_type = "circular"},
		{spell_name = "AkaliQMis1", root_type = "circular"},
		{spell_name = "AkaliQMis2", root_type = "circular"},
		{spell_name = "AkaliQMis3", root_type = "circular"},
		{spell_name = "AkaliQMis4", root_type = "circular"},
		{spell_name = "AkaliQMis5", root_type = "circular"},
		{spell_name = "AkaliQMisParent", root_type = "circular"},
		{spell_name = "AkaliW", root_type = "circular"},
		{spell_name = "AkaliWMisVis", root_type = "circular"},
		{spell_name = "AkaliWSmokeMissile", root_type = "circular"},
		{spell_name = "AkaliWSmokeMissileRiver", root_type = "circular"},
		{spell_name = "AkaliWSmokeParent", root_type = "circular"},
		{spell_name = "AkaliWSmokeParentRiver", root_type = "circular"},
		{spell_name = "AkaliE", root_type = "circular"},
		{spell_name = "AkaliEMis", root_type = "circular"},
	},
	["Akshan"] = {
		{spell_name = "AkshanQ", root_type = "linear"},
		{spell_name = "AkshanQMissile", root_type = "linear"},
		{spell_name = "AkshanE", root_type = "linear"},
		{spell_name = "AkshanE2", root_type = "circular"},
		{spell_name = "AkshanE3", root_type = "circular"},
		{spell_name = "AkshanEMissile", root_type = "linear"},
	},
	["Alistar"] = {
	},
	["Amumu"] = {
		{spell_name = "BandageToss", root_type = "circular"},
		{spell_name = "SadMummyBandageToss", root_type = "circular"},
	},
	["Anivia"] = {
		{spell_name = "GlacialStorm", root_type = "circular"},
		{spell_name = "GlacialStormSpell", root_type = "circular"},
		{spell_name = "FlashFrost", root_type = "circular"},
		{spell_name = "FlashFrostSpell", root_type = "circular"},
		{spell_name = "Crystallize", root_type = "circular"},
	},
	["Annie"] = {
		{spell_name = "AnnieW", root_type = "cone"},
	},
	["Ashe"] = {
		{spell_name = "Volley", root_type = "cone"},
		{spell_name = "VolleyAttack", root_type = "circular"},
		{spell_name = "VolleyAttackWithSound", root_type = "circular"},
		{spell_name = "VolleyCenterAttack", root_type = "circular"},
		{spell_name = "VolleyRank2", root_type = "cone"},
		{spell_name = "VolleyRank3", root_type = "cone"},
		{spell_name = "VolleyRank4", root_type = "cone"},
		{spell_name = "VolleyRank5", root_type = "cone"},
		{spell_name = "VolleyRightAttack", root_type = "circular"},
		{spell_name = "AsheSpiritOfTheHawk", root_type = "circular"},
		{spell_name = "AsheSpiritOfTheHawkCast", root_type = "circular"},
		{spell_name = "EnchantedCrystalArrow", root_type = "circular"},
	},
	["AurelionSol"] = {
		{spell_name = "AurelionSolQ", root_type = "linear"},
		{spell_name = "AurelionSolW", root_type = "circular"},
		{spell_name = "AurelionSolWToggle", root_type = "circular"},
		{spell_name = "AurelionSolE", root_type = "circular"},
		{spell_name = "AurelionSolRMissile", root_type = "circular"},
		{spell_name = "AurelionSolR2", root_type = "circular"},
		{spell_name = "AurelionSolR2Missile", root_type = "circular"},
	},
	["Azir"] = {
		{spell_name = "AzirQWrapper", root_type = "circular"},
		{spell_name = "AzirQ", root_type = "circular"},
		{spell_name = "AzirWSpawnSoldier", root_type = "circular"},
		{spell_name = "AzirEWrapper", root_type = "circular"},
		{spell_name = "AzirE", root_type = "circular"},
		{spell_name = "AzirEVisualMissile", root_type = "linear"},
		{spell_name = "AzirR", root_type = "circular"},
	},
	["Bard"] = {
		{spell_name = "BardQ", root_type = "circular"},
		{spell_name = "BardQMissile", root_type = "circular"},
		{spell_name = "BardQMissile2", root_type = "circular"},
		{spell_name = "BardWHealthPack", root_type = "circular"},
		{spell_name = "BardECreateDoor", root_type = "circular"},
		{spell_name = "BardR", root_type = "circular"},
		{spell_name = "BardRMissileFixedTravelTime", root_type = "circular"},
		{spell_name = "BardRMissileRange1", root_type = "circular"},
		{spell_name = "BardRMissileRange2", root_type = "circular"},
		{spell_name = "BardRMissileRange3", root_type = "circular"},
		{spell_name = "BardRMissileRange4", root_type = "circular"},
		{spell_name = "BardRMissileRange5", root_type = "circular"},
	},
	["Belveth"] = {
		{spell_name = "BelvethW", root_type = "circular"},
		{spell_name = "BelvethQ", root_type = "circular"},
	},
	["Blitzcrank"] = {
		{spell_name = "RocketGrab", root_type = "circular"},
		{spell_name = "RocketGrabMissile", root_type = "circular"},
		{spell_name = "PowerFistAttack", root_type = "circular"},
	},
	["Brand"] = {
		{spell_name = "BrandQ", root_type = "circular"},
		{spell_name = "BrandQMissile", root_type = "circular"},
		{spell_name = "BrandW", root_type = "circular"},
		{spell_name = "BrandAblaze", root_type = "circular"},
		{spell_name = "BrandAblazeDetonateMarker", root_type = "circular"},
	},
	["Braum"] = {
		{spell_name = "BraumQ", root_type = "circular"},
		{spell_name = "BraumQMissile", root_type = "circular"},
		{spell_name = "BraumE", root_type = "linear"},
		{spell_name = "BraumRWrapper", root_type = "circular"},
		{spell_name = "BraumRMissile", root_type = "circular"},
	},
	["Caitlyn"] = {
		{spell_name = "CaitlynQ", root_type = "linear"},
		{spell_name = "CaitlynQ2", root_type = "linear"},
		{spell_name = "CaitlynW", root_type = "circular"},
		{spell_name = "CaitlynE", root_type = "circular"},
		{spell_name = "CaitlynEMissile", root_type = "linear"},
	},
	["Camille"] = {
		{spell_name = "CamilleE", root_type = "linear"},
		{spell_name = "CamilleEDash2", root_type = "circular"},
		{spell_name = "CamilleELeftMissile", root_type = "circular"},
		{spell_name = "CamilleEMissile", root_type = "circular"},
		{spell_name = "CamilleERightMissile", root_type = "circular"},
		{spell_name = "CamilleW", root_type = "linear"},
		{spell_name = "CamilleRTether", root_type = "circular"},
	},
	["Cassiopeia"] = {
		{spell_name = "CassiopeiaQ", root_type = "circular"},
		{spell_name = "CassiopeiaW", root_type = "circular"},
		{spell_name = "CassiopeiaWMissile", root_type = "circular"},
		{spell_name = "CassiopeiaWSlow", root_type = "cone"},
		{spell_name = "CassiopeiaR", root_type = "cone"},
		{spell_name = "CassiopeiaRStun", root_type = "cone"},
	},
	["Chogath"] = {
		{spell_name = "Rupture", root_type = "circular"},
		{spell_name = "FeralScream", root_type = "cone"},
		{spell_name = "VorpalSpikesMissle", root_type = "circular"},
		{spell_name = "VorpalSpikesMissle2", root_type = "circular"},
		{spell_name = "VorpalSpikesMissle3", root_type = "circular"},
		{spell_name = "VorpalSpikesMissle4", root_type = "circular"},
		{spell_name = "VorpalSpikesMissle5", root_type = "circular"},
		{spell_name = "VorpalSpikesMissle6", root_type = "circular"},
		{spell_name = "VorpalSpikesMissle7", root_type = "circular"},
	},
	["Corki"] = {
		{spell_name = "PhosphorusBomb", root_type = "circular"},
		{spell_name = "CarpetBomb", root_type = "circular"},
		{spell_name = "CarpetBombMega", root_type = "circular"},
		{spell_name = "DangerZone", root_type = "circular"},
		{spell_name = "GGun", root_type = "cone"},
		{spell_name = "GGSpray", root_type = "cone"},
		{spell_name = "MissileBarrage", root_type = "circular"},
		{spell_name = "MissileBarrageMissile", root_type = "circular"},
		{spell_name = "MissileBarrageMissile2", root_type = "circular"},
	},
	["Darius"] = {
		{spell_name = "DariusAxeGrabCone", root_type = "cone"},
		{spell_name = "DariusHemoInternal", root_type = "circular"},
		{spell_name = "DariusHemoVisual", root_type = "circular"},
	},
	["Diana"] = {
		{spell_name = "DianaQ", root_type = "circular"},
		{spell_name = "DianaQInnerMissile", root_type = "linear"},
		{spell_name = "DianaQOuterMissile", root_type = "linear"},
	},
	["DrMundo"] = {
		{spell_name = "DrMundoQ", root_type = "circular"},
		{spell_name = "DrMundoPObjectMissile", root_type = "circular"},
	},
	["Draven"] = {
		{spell_name = "DravenRCast", root_type = "circular"},
		{spell_name = "DravenR", root_type = "circular"},
		{spell_name = "DravenSpinningReturn", root_type = "circular"},
		{spell_name = "DravenSpinningReturnCatch", root_type = "circular"},
		{spell_name = "DravenSpinningReturnLeftAxe", root_type = "circular"},
		{spell_name = "DravenDoubleShot", root_type = "circular"},
		{spell_name = "DravenDoubleShotMissile", root_type = "circular"},
	},
	["Ekko"] = {
		{spell_name = "EkkoQ", root_type = "circular"},
		{spell_name = "EkkoQMis", root_type = "circular"},
		{spell_name = "EkkoQReturnDead", root_type = "linear"},
		{spell_name = "EkkoW", root_type = "circular"},
		{spell_name = "EkkoE", root_type = "circular"},
	},
	["Elise"] = {
		{spell_name = "EliseHumanW", root_type = "linear"},
		{spell_name = "EliseHumanE", root_type = "linear"},
	},
	["Evelynn"] = {
		{spell_name = "EvelynnQ", root_type = "circular"},
		{spell_name = "EvelynnR", root_type = "circular"},
		{spell_name = "EvelynnRTrail", root_type = "circular"},
	},
	["Ezreal"] = {
		{spell_name = "EzrealQ", root_type = "linear"},
		{spell_name = "EzrealW", root_type = "linear"},
		{spell_name = "EzrealE", root_type = "circular"},
		{spell_name = "EzrealR", root_type = "circular"},
	},
	["FiddleSticks"] = {
		{spell_name = "FiddleSticksE", root_type = "circular"},
		{spell_name = "FiddleSticksR", root_type = "circular"},
	},
	["Fiora"] = {
		{spell_name = "FioraQ", root_type = "linear"},
		{spell_name = "FioraW", root_type = "circular"},
		{spell_name = "FioraWMissile", root_type = "circular"},
		{spell_name = "FioraWMissile2", root_type = "circular"},
	},
	["Fizz"] = {
		{spell_name = "FizzE", root_type = "circular"},
		{spell_name = "FizzEBuffer", root_type = "circular"},
		{spell_name = "FizzETwo", root_type = "circular"},
		{spell_name = "FizzR", root_type = "circular"},
		{spell_name = "FizzRMissile", root_type = "circular"},
	},
	["Galio"] = {
		{spell_name = "GalioQ", root_type = "circular"},
		{spell_name = "GalioQMissile", root_type = "linear"},
		{spell_name = "GalioQMissileR", root_type = "linear"},
		{spell_name = "GalioQSuper", root_type = "linear"},
		{spell_name = "GalioE", root_type = "circular"},
	},
	["Gangplank"] = {
		{spell_name = "GangplankE", root_type = "circular"},
		{spell_name = "GangplankESpellPassive", root_type = "circular"},
		{spell_name = "GangplankEBarrelFuseMissile", root_type = "circular"},
		{spell_name = "GangplankR", root_type = "circular"},
		{spell_name = "GangplankRWithRaiseMorale", root_type = "circular"},
	},
	["Garen"] = {
	},
	["Gnar"] = {
		{spell_name = "GnarQ", root_type = "circular"},
		{spell_name = "GnarQMissile", root_type = "circular"},
		{spell_name = "GnarQMissileReturn", root_type = "circular"},
		{spell_name = "GnarBigQ", root_type = "circular"},
		{spell_name = "GnarBigQMissile", root_type = "circular"},
		{spell_name = "GnarBigW", root_type = "circular"},
		{spell_name = "GnarBigE", root_type = "circular"},
		{spell_name = "GnarE", root_type = "circular"},
		{spell_name = "GnarR", root_type = "linear"},
	},
	["Gragas"] = {
		{spell_name = "GragasQ", root_type = "circular"},
		{spell_name = "GragasQMissile", root_type = "circular"},
		{spell_name = "GragasQSpellPassive", root_type = "circular"},
		{spell_name = "GragasE", root_type = "circular"},
		{spell_name = "GragasR", root_type = "circular"},
		{spell_name = "GragasRBoom", root_type = "circular"},
	},
	["Graves"] = {
		{spell_name = "GravesQLineSpell", root_type = "cone"},
		{spell_name = "GravesQChargeUp", root_type = "circular"},
		{spell_name = "GravesQChargeUp2", root_type = "linear"},
		{spell_name = "GravesQChargeUpDummy", root_type = "cone"},
		{spell_name = "GravesQLineMis", root_type = "circular"},
		{spell_name = "GravesQPress1", root_type = "circular"},
		{spell_name = "GravesQPress2", root_type = "circular"},
		{spell_name = "GravesQZoneSpell", root_type = "cone"},
		{spell_name = "GravesQReturn", root_type = "circular"},
		{spell_name = "GravesQChargeUpSelfSlow", root_type = "linear"},
		{spell_name = "GravesQZoneMis", root_type = "circular"},
		{spell_name = "GravesSmokeGrenade", root_type = "circular"},
		{spell_name = "GravesMove", root_type = "circular"},
		{spell_name = "GravesChargeShot", root_type = "circular"},
		{spell_name = "GravesChargeShotFxMissile", root_type = "circular"},
		{spell_name = "GravesChargeShotFxMissile2", root_type = "circular"},
		{spell_name = "GravesChargeShotShot", root_type = "circular"},
		{spell_name = "GravesChargeShotXplode", root_type = "cone"},
	},
	["Gwen"] = {
		{spell_name = "GwenR", root_type = "linear"},
		{spell_name = "GwenRMis", root_type = "linear"},
		{spell_name = "GwenRMis_VisualOnly", root_type = "linear"},
		{spell_name = "GwenRMis3_VisualOnly", root_type = "linear"},
		{spell_name = "GwenRRecast", root_type = "linear"},
		{spell_name = "GwenQ", root_type = "linear"},
		{spell_name = "GwenE", root_type = "circular"},
	},
	["Hecarim"] = {
		{spell_name = "HecarimUlt", root_type = "circular"},
		{spell_name = "HecarimUltCharge", root_type = "circular"},
		{spell_name = "HecarimUltMissile", root_type = "circular"},
		{spell_name = "HecarimUltMissileGrab", root_type = "circular"},
		{spell_name = "HecarimUltMissileGrabEmpty", root_type = "circular"},
		{spell_name = "HecarimUltMissileSkn4Audio", root_type = "circular"},
		{spell_name = "HecarimUltMissileSkn4C", root_type = "circular"},
		{spell_name = "HecarimUltMissileSkn4L1", root_type = "circular"},
		{spell_name = "HecarimUltMissileSkn4L2", root_type = "circular"},
		{spell_name = "HecarimUltMissileSkn4R1", root_type = "circular"},
		{spell_name = "HecarimUltMissileSkn4R2", root_type = "circular"},
		{spell_name = "HecarimCharge", root_type = "linear"},
		{spell_name = "HecarimChargeCharge", root_type = "circular"},
	},
	["Heimerdinger"] = {
		{spell_name = "HeimerdingerQUlt", root_type = "circular"},
		{spell_name = "HeimerdingerEUlt", root_type = "circular"},
		{spell_name = "HeimerdingerWUlt", root_type = "circular"},
		{spell_name = "HeimerdingerQ", root_type = "circular"},
		{spell_name = "HeimerdingerW", root_type = "circular"},
		{spell_name = "HeimerdingerWAttack2", root_type = "circular"},
		{spell_name = "HeimerdingerWAttack2_Ult", root_type = "circular"},
		{spell_name = "HeimerdingerWAttack2Ult", root_type = "circular"},
		{spell_name = "HeimerdingerE", root_type = "circular"},
		{spell_name = "HeimerdingerE_Ult", root_type = "circular"},
	},
	["Illaoi"] = {
		{spell_name = "IllaoiQ", root_type = "circular"},
		{spell_name = "IllaoiE", root_type = "circular"},
		{spell_name = "IllaoiEMis", root_type = "linear"},
		{spell_name = "IllaoiR", root_type = "circular"},
	},
	["Irelia"] = {
		{spell_name = "IreliaW", root_type = "linear"},
		{spell_name = "IreliaW2", root_type = "linear"},
		{spell_name = "IreliaE", root_type = "circular"},
		{spell_name = "IreliaE2", root_type = "circular"},
		{spell_name = "IreliaEMissile", root_type = "linear"},
		{spell_name = "IreliaEParticleMissile", root_type = "circular"},
		{spell_name = "IreliaESecondary", root_type = "linear"},
		{spell_name = "IreliaR", root_type = "linear"},
		{spell_name = "IreliaR2", root_type = "linear"},
	},
	["Ivern"] = {
		{spell_name = "IvernR", root_type = "circular"},
		{spell_name = "IvernRMissile", root_type = "circular"},
		{spell_name = "IvernQ", root_type = "linear"},
	},
	["Janna"] = {
		{spell_name = "HowlingGale", root_type = "linear"},
		{spell_name = "HowlingGale_URF", root_type = "linear"},
		{spell_name = "HowlingGaleSpell", root_type = "circular"},
	},
	["JarvanIV"] = {
		{spell_name = "JarvanIVDragonStrike", root_type = "linear"},
		{spell_name = "JarvanIVDemacianStandard", root_type = "circular"},
	},
	["Jax"] = {
	},
	["Jayce"] = {
		{spell_name = "JayceAccelerationGate", root_type = "circular"},
		{spell_name = "JayceShockBlast", root_type = "linear"},
		{spell_name = "JayceShockBlastMis", root_type = "circular"},
		{spell_name = "JayceShockBlastWallMis", root_type = "linear"},
	},
	["Jhin"] = {
		{spell_name = "JhinRShotMis", root_type = "circular"},
		{spell_name = "JhinRShotMis4", root_type = "circular"},
		{spell_name = "JhinRShot", root_type = "circular"},
		{spell_name = "JhinW", root_type = "linear"},
		{spell_name = "JhinE", root_type = "circular"},
		{spell_name = "JhinETrap", root_type = "circular"},
	},
	["Jinx"] = {
		{spell_name = "JinxR", root_type = "circular"},
		{spell_name = "JinxE", root_type = "circular"},
		{spell_name = "JinxEMine", root_type = "circular"},
		{spell_name = "JinxEHit", root_type = "circular"},
		{spell_name = "JinxW", root_type = "circular"},
		{spell_name = "JinxWMissile", root_type = "circular"},
	},
	["KSante"] = {
		{spell_name = "KSanteQ", root_type = "circular"},
		{spell_name = "KSanteQ3", root_type = "circular"},
		{spell_name = "KSanteQ3Missile", root_type = "linear"},
		{spell_name = "KSanteW", root_type = "linear"},
	},
	["Kaisa"] = {
		{spell_name = "KaisaW", root_type = "circular"},
		{spell_name = "KaisaR", root_type = "circular"},
	},
	["Kalista"] = {
		{spell_name = "KalistaMysticShot", root_type = "circular"},
		{spell_name = "KalistaMysticShotMis", root_type = "circular"},
		{spell_name = "KalistaMysticShotMissile", root_type = "circular"},
		{spell_name = "KalistaMysticShotMisTrue", root_type = "circular"},
		{spell_name = "KalistaW", root_type = "circular"},
		{spell_name = "KalistaRAlly", root_type = "circular"},
		{spell_name = "KalistaRAllyDash", root_type = "linear"},
		{spell_name = "KalistaRMis", root_type = "circular"},
		{spell_name = "KalistaPassiveDashSpellActual", root_type = "circular"},
		{spell_name = "KalistaPassiveDashTargeter", root_type = "circular"},
		{spell_name = "KalistaPInvocation", root_type = "circular"},
	},
	["Karma"] = {
		{spell_name = "KarmaQ", root_type = "circular"},
		{spell_name = "KarmaQMissile", root_type = "circular"},
		{spell_name = "KarmaQMissileMantra", root_type = "circular"},
	},
	["Karthus"] = {
		{spell_name = "KarthusLayWasteA1", root_type = "circular"},
		{spell_name = "KarthusLayWaste2", root_type = "circular"},
		{spell_name = "KarthusLayWasteA2", root_type = "circular"},
		{spell_name = "KarthusLayWasteA3", root_type = "circular"},
		{spell_name = "KarthusLayWasteDeadA1", root_type = "circular"},
		{spell_name = "KarthusLayWasteDeadA2", root_type = "circular"},
		{spell_name = "KarthusLayWasteDeadA3", root_type = "circular"},
		{spell_name = "KarthusWallOfPain", root_type = "circular"},
		{spell_name = "KarthusWallOfPain2", root_type = "circular"},
		{spell_name = "KarthusLayWaste", root_type = "circular"},
	},
	["Kassadin"] = {
		{spell_name = "ForcePulse", root_type = "cone"},
		{spell_name = "RiftWalk", root_type = "circular"},
	},
	["Katarina"] = {
		{spell_name = "KatarinaEWrapper", root_type = "circular"},
		{spell_name = "KatarinaEDagger", root_type = "circular"},
		{spell_name = "KatarinaETrail", root_type = "circular"},
		{spell_name = "KatarinaPickupPBAoE", root_type = "circular"},
	},
	["Kayle"] = {
		{spell_name = "KayleQ", root_type = "circular"},
		{spell_name = "KayleQMis", root_type = "circular"},
		{spell_name = "KayleQMisVFX", root_type = "circular"},
		{spell_name = "KayleEnrageConeMisVFX2", root_type = "circular"},
		{spell_name = "KayleEnrageConeMisVFX", root_type = "circular"},
		{spell_name = "KayleEnrageConeMisUpgrade", root_type = "circular"},
		{spell_name = "KayleEnrageConeMis", root_type = "circular"},
	},
	["Kayn"] = {
		{spell_name = "KaynRJumpOut", root_type = "circular"},
		{spell_name = "KaynW", root_type = "circular"},
		{spell_name = "KaynAssW", root_type = "circular"},
		{spell_name = "KaynAssWJumpOut", root_type = "circular"},
		{spell_name = "KaynQ", root_type = "circular"},
	},
	["Kennen"] = {
		{spell_name = "KennenShurikenHurlMissile1", root_type = "linear"},
		{spell_name = "KennenShurikenHurl1", root_type = "circular"},
	},
	["Khazix"] = {
		{spell_name = "KhazixW", root_type = "circular"},
		{spell_name = "KhazixWLong", root_type = "cone"},
		{spell_name = "KhazixWMissile", root_type = "circular"},
		{spell_name = "KhazixE", root_type = "circular"},
		{spell_name = "KhazixELong", root_type = "circular"},
		{spell_name = "KhazixEInvisMissile", root_type = "circular"},
	},
	["Kindred"] = {
		{spell_name = "KindredQ", root_type = "circular"},
		{spell_name = "KindredQ_URFWrapper", root_type = "circular"},
		{spell_name = "KindredRNoDeathBuff", root_type = "circular"},
	},
	["Kled"] = {
		{spell_name = "KledR", root_type = "circular"},
		{spell_name = "KledQ", root_type = "circular"},
		{spell_name = "KledQMissile", root_type = "circular"},
		{spell_name = "KledE", root_type = "circular"},
		{spell_name = "KledE2Dash", root_type = "circular"},
		{spell_name = "KledEDash", root_type = "circular"},
		{spell_name = "KledRiderQ", root_type = "circular"},
		{spell_name = "KledRiderQMissile", root_type = "circular"},
	},
	["KogMaw"] = {
		{spell_name = "KogMawQ", root_type = "linear"},
		{spell_name = "KogMawQMis", root_type = "circular"},
		{spell_name = "KogMawVoidOoze", root_type = "circular"},
		{spell_name = "KogMawVoidOozeMissile", root_type = "circular"},
		{spell_name = "KogMawLivingArtillery", root_type = "circular"},
	},
	["Leblanc"] = {
		{spell_name = "LeblancRW", root_type = "circular"},
		{spell_name = "LeblancRWReturn", root_type = "circular"},
		{spell_name = "LeblancW", root_type = "circular"},
		{spell_name = "LeblancWMove", root_type = "circular"},
		{spell_name = "LeblancWReturn", root_type = "circular"},
		{spell_name = "LeblancE", root_type = "circular"},
		{spell_name = "LeblancEMissile", root_type = "linear"},
		{spell_name = "LeblancR", root_type = "circular"},
		{spell_name = "LeblancRE", root_type = "circular"},
		{spell_name = "LeblancREMissile", root_type = "linear"},
		{spell_name = "LeblancRREMissile", root_type = "linear"},
	},
	["LeeSin"] = {
		{spell_name = "BlindMonkQOne", root_type = "linear"},
	},
	["Leona"] = {
		{spell_name = "LeonaZenithBlade", root_type = "circular"},
		{spell_name = "LeonaZenithBladeMissile", root_type = "circular"},
		{spell_name = "LeonaSolarFlare", root_type = "circular"},
	},
	["Lillia"] = {
		{spell_name = "LilliaQSpellPassive", root_type = "circular"},
		{spell_name = "LilliaPranceStack", root_type = "circular"},
		{spell_name = "LilliaW", root_type = "circular"},
		{spell_name = "LilliaE", root_type = "circular"},
		{spell_name = "LilliaERollingMissile", root_type = "circular"},
		{spell_name = "LilliaERollingMissileShort", root_type = "circular"},
		{spell_name = "LilliaESpellPassive", root_type = "circular"},
	},
	["Lissandra"] = {
		{spell_name = "LissandraQ", root_type = "circular"},
		{spell_name = "LissandraQMissile", root_type = "circular"},
		{spell_name = "LissandraWFrozen", root_type = "circular"},
		{spell_name = "LissandraE", root_type = "circular"},
		{spell_name = "LissandraEBuffer", root_type = "linear"},
		{spell_name = "LissandraEDamage", root_type = "circular"},
		{spell_name = "LissandraEMissile", root_type = "circular"},
	},
	["Lucian"] = {
		{spell_name = "LucianR", root_type = "linear"},
		{spell_name = "LucianRMissile", root_type = "linear"},
		{spell_name = "LucianRMissileOffhand", root_type = "linear"},
		{spell_name = "LucianW", root_type = "circular"},
		{spell_name = "LucianWMissile", root_type = "linear"},
		{spell_name = "LucianE", root_type = "circular"},
		{spell_name = "LucianPassiveShotDummy", root_type = "linear"},
	},
	["Lulu"] = {
		{spell_name = "LuluQ", root_type = "circular"},
		{spell_name = "LuluQMissile", root_type = "circular"},
		{spell_name = "LuluQMissileTwo", root_type = "circular"},
		{spell_name = "LuluPassiveMissileController", root_type = "circular"},
	},
	["Lux"] = {
		{spell_name = "LuxR", root_type = "circular"},
		{spell_name = "LuxRVfxMis", root_type = "circular"},
		{spell_name = "LuxLightBinding", root_type = "circular"},
		{spell_name = "LuxLightBindingDummy", root_type = "linear"},
		{spell_name = "LuxLightBindingMis", root_type = "linear"},
		{spell_name = "LuxPrismaticWave", root_type = "circular"},
		{spell_name = "LuxPrismaticWaveMissile", root_type = "circular"},
		{spell_name = "LuxPrismaticWaveReturnDead", root_type = "linear"},
		{spell_name = "LuxLightStrikeKugel", root_type = "circular"},
	},
	["Malphite"] = {
		{spell_name = "UFSlash", root_type = "circular"},
	},
	["Malzahar"] = {
		{spell_name = "MalzaharQ", root_type = "circular"},
		{spell_name = "MalzaharQMissile", root_type = "circular"},
		{spell_name = "MalzaharW", root_type = "circular"},
	},
	["Maokai"] = {
		{spell_name = "MaokaiQ", root_type = "circular"},
		{spell_name = "MaokaiQMissile", root_type = "circular"},
		{spell_name = "MaokaiE", root_type = "circular"},
		{spell_name = "MaokaiEMissile", root_type = "circular"},
		{spell_name = "MaokaiEMissileBrush", root_type = "circular"},
		{spell_name = "MaokaiR", root_type = "circular"},
		{spell_name = "MaokaiRMis", root_type = "circular"},
		{spell_name = "MaokaiRMisExtra", root_type = "circular"},
		{spell_name = "MaokaiRSoundMis", root_type = "circular"},
	},
	["MasterYi"] = {
		{spell_name = "AlphaStrikeMissileReturn", root_type = "circular"},
	},
	["MissFortune"] = {
		{spell_name = "MissFortuneBulletTime", root_type = "cone"},
		{spell_name = "MissFortuneBullets", root_type = "linear"},
		{spell_name = "MissFortuneBulletEMPTY", root_type = "cone"},
		{spell_name = "MissFortuneScattershot", root_type = "circular"},
		{spell_name = "MissFortuneRicochetShotDud", root_type = "circular"},
	},
	["MonkeyKing"] = {
		{spell_name = "MonkeyKingDecoy", root_type = "circular"},
	},
	["Mordekaiser"] = {
		{spell_name = "MordekaiserQ", root_type = "circular"},
		{spell_name = "MordekaiserE", root_type = "circular"},
		{spell_name = "MordekaiserEMissile", root_type = "circular"},
	},
	["Morgana"] = {
		{spell_name = "MorganaQ", root_type = "linear"},
		{spell_name = "MorganaW", root_type = "circular"},
	},
	["Nami"] = {
		{spell_name = "NamiR", root_type = "linear"},
		{spell_name = "NamiRMissile", root_type = "circular"},
		{spell_name = "NamiQ", root_type = "circular"},
		{spell_name = "NamiQDebuff", root_type = "circular"},
		{spell_name = "NamiQDummyMissile", root_type = "circular"},
	},
	["Nasus"] = {
		{spell_name = "NasusE", root_type = "circular"},
	},
	["Nautilus"] = {
		{spell_name = "NautilusAnchorDrag", root_type = "circular"},
		{spell_name = "NautilusAnchorDragMissile", root_type = "linear"},
		{spell_name = "NautilusSplashZoneSplash", root_type = "linear"},
	},
	["Neeko"] = {
		{spell_name = "NeekoQ", root_type = "circular"},
		{spell_name = "NeekoW", root_type = "linear"},
		{spell_name = "NeekoE", root_type = "linear"},
	},
	["Nidalee"] = {
		{spell_name = "JavelinToss", root_type = "linear"},
		{spell_name = "Bushwhack", root_type = "circular"},
	},
	["Nilah"] = {
		{spell_name = "NilahQ", root_type = "circular"},
		{spell_name = "NilahEQMis", root_type = "circular"},
		{spell_name = "NilahE", root_type = "Target"},
		{spell_name = "NilahPassive", root_type = "circular"},
	},
	["Nocturne"] = {
		{spell_name = "NocturneDuskbringer", root_type = "linear"},
	},
	["Nunu"] = {
		{spell_name = "NunuR_Recast", root_type = "circular"},
		{spell_name = "NunuW", root_type = "circular"},
		{spell_name = "NunuW_Recast", root_type = "circular"},
		{spell_name = "NunuWSnowballMissile", root_type = "circular"},
		{spell_name = "NunuE", root_type = "circular"},
		{spell_name = "NunuESnowballBurstFire", root_type = "circular"},
		{spell_name = "NunuESnowballMissile", root_type = "circular"},
	},
	["Olaf"] = {
		{spell_name = "OlafAxeThrowCast", root_type = "linear"},
		{spell_name = "OlafAxeThrow", root_type = "linear"},
		{spell_name = "OlafAxeThrowDamage", root_type = "linear"},
		{spell_name = "OlafRagnarokPassiveBuff", root_type = "linear"},
	},
	["Orianna"] = {
		{spell_name = "OrianaIzunaCommand", root_type = "circular"},
		{spell_name = "OrianaIzuna", root_type = "linear"},
	},
	["Ornn"] = {
		{spell_name = "OrnnR", root_type = "circular"},
		{spell_name = "OrnnQ", root_type = "linear"},
		{spell_name = "OrnnW", root_type = "circular"},
		{spell_name = "OrnnVulnerableDebuff", root_type = "circular"},
		{spell_name = "OrnnE", root_type = "circular"},
		{spell_name = "OrnnPAllyItemReady", root_type = "circular"},
		{spell_name = "OrnnPItemCurrency", root_type = "circular"},
	},
	["Pantheon"] = {
		{spell_name = "PantheonR", root_type = "circular"},
		{spell_name = "PantheonRFall", root_type = "circular"},
		{spell_name = "PantheonRMissile", root_type = "circular"},
		{spell_name = "PantheonRMissile2", root_type = "circular"},
		{spell_name = "PantheonRMissile3", root_type = "circular"},
		{spell_name = "PantheonQ", root_type = "linear"},
		{spell_name = "PantheonQMissile", root_type = "circular"},
		{spell_name = "PantheonQTap", root_type = "circular"},
		{spell_name = "PantheonE", root_type = "linear"},
		{spell_name = "PantheonEShieldSlam", root_type = "circular"},
	},
	["Poppy"] = {
		{spell_name = "PoppyQ", root_type = "circular"},
		{spell_name = "PoppyQSpell", root_type = "circular"},
		{spell_name = "PoppyR", root_type = "linear"},
		{spell_name = "PoppyRMissile", root_type = "circular"},
		{spell_name = "PoppyRSpell", root_type = "circular"},
		{spell_name = "PoppyRSpellInstant", root_type = "circular"},
	},
	["Pyke"] = {
		{spell_name = "PykeR", root_type = "circular"},
		{spell_name = "PykeRSpellPassive", root_type = "circular"},
		{spell_name = "PykeRTrail", root_type = "circular"},
		{spell_name = "PykeQ", root_type = "linear"},
		{spell_name = "PykeQMelee", root_type = "circular"},
		{spell_name = "PykeQRange", root_type = "circular"},
		{spell_name = "PykeE", root_type = "circular"},
	},
	["Qiyana"] = {
		{spell_name = "QiyanaQ", root_type = "circular"},
		{spell_name = "QiyanaQ_Grass", root_type = "linear"},
		{spell_name = "QiyanaQ_Water", root_type = "linear"},
		{spell_name = "QiyanaQ_Rock", root_type = "linear"},
		{spell_name = "QiyanaR", root_type = "circular"},
		{spell_name = "QiyanaRMis", root_type = "linear"},
		{spell_name = "QiyanaRWallHitMis", root_type = "linear"},
		{spell_name = "QiyanaRWallFollowMis", root_type = "linear"},
		{spell_name = "QiyanaRWallFollowMisShadow", root_type = "linear"},
		{spell_name = "QiyanaRWallFollowMisShadowCounterClockwise", root_type = "linear"},
	},
	["Quinn"] = {
		{spell_name = "QuinnQ", root_type = "linear"},
		{spell_name = "QuinnWTimingMissile", root_type = "circular"},
	},
	["Rakan"] = {
		{spell_name = "RakanQ", root_type = "circular"},
		{spell_name = "RakanQMis", root_type = "circular"},
		{spell_name = "RakanW", root_type = "circular"},
	},
	["Rammus"] = {
		{spell_name = "Tremors2", root_type = "circular"},
	},
	["RekSai"] = {
		{spell_name = "RekSaiQBurrowed", root_type = "circular"},
		{spell_name = "RekSaiQBurrowedMis", root_type = "circular"},
		{spell_name = "RekSaiEBurrowed", root_type = "circular"},
	},
	["Rell"] = {
		{spell_name = "RellQ", root_type = "linear"},
		{spell_name = "RellQ_VFXMis", root_type = "circular"},
		{spell_name = "RellW_Dismount", root_type = "circular"},
		{spell_name = "RellE", root_type = "circular"},
		{spell_name = "RellE_StunCast", root_type = "circular"},
	},
	["Renata"] = {
		{spell_name = "RenataQ", root_type = "linear"},
		{spell_name = "RenataQRecast", root_type = "circular"},
		{spell_name = "RenataE", root_type = "circular"},
		{spell_name = "RenataR", root_type = "linear"},
		{spell_name = "RenataRMissile", root_type = "circular"},
		{spell_name = "RenataRMissileSides", root_type = "circular"},
	},
	["Renekton"] = {
		{spell_name = "RenektonSliceAndDice", root_type = "circular"},
		{spell_name = "RenektonDice", root_type = "circular"},
	},
	["Rengar"] = {
		{spell_name = "RengarE", root_type = "circular"},
		{spell_name = "RengarEMis", root_type = "circular"},
		{spell_name = "RengarEEmp", root_type = "circular"},
		{spell_name = "RengarEEmpMis", root_type = "circular"},
	},
	["Riven"] = {
		{spell_name = "RivenIzunaBlade", root_type = "cone"},
		{spell_name = "RivenTriCleaveBuffer", root_type = "circular"},
		{spell_name = "RivenTriCleaveBufferB", root_type = "circular"},
		{spell_name = "RivenTriCleaveDamage", root_type = "circular"},
	},
	["Rumble"] = {
		{spell_name = "RumbleFlameThrower", root_type = "cone"},
		{spell_name = "RumbleFlameThrowerSpray", root_type = "cone"},
		{spell_name = "RumbleFlameThrowerSpraySuper", root_type = "cone"},
		{spell_name = "RumbleGrenade", root_type = "circular"},
		{spell_name = "RumbleGrenadeMissile", root_type = "linear"},
		{spell_name = "RumbleGrenadeMissileDangerZone", root_type = "linear"},
		{spell_name = "RumbleCarpetBombMissile", root_type = "circular"},
	},
	["Ryze"] = {
		{spell_name = "RyzeQWrapper", root_type = "linear"},
		{spell_name = "RyzeQ", root_type = "linear"},
		{spell_name = "RyzeR", root_type = "circular"},
		{spell_name = "RyzeR2", root_type = "circular"},
	},
	["Samira"] = {
		{spell_name = "SamiraQ", root_type = "circular"},
		{spell_name = "SamiraQGun", root_type = "circular"},
	},
	["Sejuani"] = {
		{spell_name = "SejuaniQ", root_type = "circular"},
		{spell_name = "SejuaniW", root_type = "linear"},
		{spell_name = "SejuaniR", root_type = "circular"},
	},
	["Senna"] = {
		{spell_name = "SennaRAlly", root_type = "circular"},
		{spell_name = "SennaRWarningMis", root_type = "circular"},
		{spell_name = "SennaR", root_type = "circular"},
		{spell_name = "SennaQ", root_type = "Target"},
		{spell_name = "SennaW", root_type = "linear"},
	},
	["Seraphine"] = {
		{spell_name = "SeraphineQ", root_type = "circular"},
		{spell_name = "SeraphineE", root_type = "linear"},
		{spell_name = "SeraphineR", root_type = "circular"},
	},
	["Sett"] = {
		{spell_name = "SettW", root_type = "circular"},
		{spell_name = "SettE", root_type = "circular"},
	},
	["Shaco"] = {
		{spell_name = "HallucinateFull", root_type = "circular"},
		{spell_name = "HallucinateGuide", root_type = "circular"},
		{spell_name = "Deceive", root_type = "circular"},
		{spell_name = "JackInTheBox", root_type = "circular"},
	},
	["Shen"] = {
		{spell_name = "ShenE", root_type = "circular"},
	},
	["Shyvana"] = {
		{spell_name = "ShyvanaTransformCast", root_type = "circular"},
		{spell_name = "ShyvanaFireball", root_type = "circular"},
	},
	["Singed"] = {
		{spell_name = "MegaAdhesive", root_type = "circular"},
	},
	["Sion"] = {
		{spell_name = "SionR", root_type = "circular"},
		{spell_name = "SionQ", root_type = "linear"},
		{spell_name = "SionE", root_type = "circular"},
		{spell_name = "SionEMissile", root_type = "circular"},
	},
	["Sivir"] = {
		{spell_name = "SivirQ", root_type = "circular"},
	},
	["Skarner"] = {
		{spell_name = "SkarnerFracture", root_type = "circular"},
	},
	["Sona"] = {
		{spell_name = "SonaR", root_type = "linear"},
	},
	["Soraka"] = {
		{spell_name = "SorakaQ", root_type = "circular"},
		{spell_name = "SorakaE", root_type = "circular"},
	},
	["Swain"] = {
		{spell_name = "SwainQ", root_type = "circular"},
		{spell_name = "SwainW", root_type = "circular"},
		{spell_name = "SwainE", root_type = "linear"},
	},
	["Sylas"] = {
		{spell_name = "SylasQ", root_type = "circular"},
		{spell_name = "SylasE", root_type = "circular"},
		{spell_name = "SylasE2", root_type = "circular"},
	},
	["Syndra"] = {
		{spell_name = "SyndraQ", root_type = "circular"},
		{spell_name = "SyndraW", root_type = "circular"},
		{spell_name = "SyndraWCast", root_type = "circular"},
		{spell_name = "SyndraWDebuff", root_type = "circular"},
		{spell_name = "SyndraE", root_type = "cone"},
		{spell_name = "SyndraE5", root_type = "cone"},
		{spell_name = "SyndraE5Sound", root_type = "circular"},
		{spell_name = "SyndraEDebuff", root_type = "circular"},
		{spell_name = "SyndraEMissile2", root_type = "circular"},
		{spell_name = "SyndraEMissile3", root_type = "circular"},
		{spell_name = "SyndraESound", root_type = "circular"},
		{spell_name = "SyndraESphereMissile", root_type = "circular"},
		{spell_name = "SyndraEMissile", root_type = "circular"},
	},
	["TahmKench"] = {
		{spell_name = "TahmKenchR2", root_type = "circular"},
		{spell_name = "TahmKenchRTargetAlly", root_type = "linear"},
		{spell_name = "TahmKenchW", root_type = "circular"},
	},
	["Taliyah"] = {
		{spell_name = "TaliyahR", root_type = "circular"},
		{spell_name = "TaliyahRNoClick", root_type = "circular"},
		{spell_name = "TaliyahRBlowUpSoundMis", root_type = "circular"},
		{spell_name = "TaliyahRCurve", root_type = "circular"},
		{spell_name = "TaliyahRMis", root_type = "circular"},
		{spell_name = "TaliyahRPreMis", root_type = "circular"},
		{spell_name = "TaliyahRTerrainProto", root_type = "circular"},
		{spell_name = "TaliyahQ", root_type = "linear"},
		{spell_name = "TaliyahQMis", root_type = "linear"},
		{spell_name = "TaliyahQReturnMis", root_type = "circular"},
		{spell_name = "TaliyahQMisBig", root_type = "linear"},
		{spell_name = "TaliyahW", root_type = "circular"},
		{spell_name = "TaliyahWNoClick", root_type = "circular"},
		{spell_name = "TaliyahE", root_type = "circular"},
		{spell_name = "TaliyahESoundBlowupMis", root_type = "circular"},
		{spell_name = "TaliyahESoundMis", root_type = "circular"},
	},
	["Talon"] = {
		{spell_name = "TalonRMisOne", root_type = "circular"},
		{spell_name = "TalonW", root_type = "cone"},
		{spell_name = "TalonWMissileOne", root_type = "circular"},
		{spell_name = "TalonWMissileTwo", root_type = "circular"},
		{spell_name = "TalonE", root_type = "circular"},
		{spell_name = "TalonE2", root_type = "circular"},
	},
	["Taric"] = {
		{spell_name = "TaricE", root_type = "circular"},
	},
	["Teemo"] = {
		{spell_name = "TeemoRCast", root_type = "circular"},
		{spell_name = "BantamTrap", root_type = "circular"},
		{spell_name = "BantamTrapBounceSpell", root_type = "circular"},
		{spell_name = "BantamTrapShort", root_type = "circular"},
	},
	["Thresh"] = {
		{spell_name = "ThreshQ", root_type = "circular"},
		{spell_name = "ThreshQInternal", root_type = "circular"},
		{spell_name = "ThreshQMissile", root_type = "linear"},
		{spell_name = "ThreshQPullMissile", root_type = "linear"},
		{spell_name = "ThreshW", root_type = "circular"},
		{spell_name = "ThreshE", root_type = "linear"},
		{spell_name = "ThreshEMissile1", root_type = "circular"},
	},
	["Tristana"] = {
		{spell_name = "TristanaW", root_type = "circular"},
	},
	["Trundle"] = {
		{spell_name = "trundledesecrate", root_type = "circular"},
		{spell_name = "TrundleCircle", root_type = "circular"},
	},
	["Tryndamere"] = {
		{spell_name = "TryndamereE", root_type = "circular"},
	},
	["TwistedFate"] = {
		{spell_name = "Gate", root_type = "circular"},
		{spell_name = "WildCards", root_type = "circular"},
	},
	["Twitch"] = {
		{spell_name = "TwitchVenomCask", root_type = "circular"},
		{spell_name = "TwitchVenomCaskDebuff", root_type = "circular"},
	},
	["Udyr"] = {
	},
	["Urgot"] = {
		{spell_name = "UrgotR", root_type = "circular"},
		{spell_name = "UrgotE", root_type = "circular"},
		{spell_name = "UrgotEDash", root_type = "circular"},
		{spell_name = "UrgotQ", root_type = "circular"},
		{spell_name = "UrgotQMissile", root_type = "circular"},
		{spell_name = "UrgotQMissileExtraSkin03", root_type = "circular"},
		{spell_name = "UrgotQMissileSkin03", root_type = "circular"},
	},
	["Varus"] = {
		{spell_name = "VarusQ", root_type = "linear"},
		{spell_name = "VarusE", root_type = "circular"},
		{spell_name = "VarusR", root_type = "circular"},
	},
	["Vayne"] = {
		{spell_name = "VayneTumble", root_type = "circular"},
	},
	["Veigar"] = {
		{spell_name = "VeigarBalefulStrike", root_type = "circular"},
		{spell_name = "VeigarDarkMatter", root_type = "circular"},
		{spell_name = "VeigarEventHorizon", root_type = "circular"},
	},
	["Velkoz"] = {
		{spell_name = "VelkozQ", root_type = "circular"},
		{spell_name = "VelkozW", root_type = "circular"},
		{spell_name = "VelkozE", root_type = "circular"},
		{spell_name = "VelkozR", root_type = "linear"},
	},
	["Vex"] = {
		{spell_name = "VexR", root_type = "linear"},
		{spell_name = "VexQ", root_type = "circular"},
		{spell_name = "VexE", root_type = "circular"},
	},
	["Vi"] = {
		{spell_name = "ViQ", root_type = "linear"},
	},
	["Viego"] = {
		{spell_name = "ViegoQ", root_type = "linear"},
		{spell_name = "ViegoW", root_type = "linear"},
		{spell_name = "ViegoWMis", root_type = "circular"},
		{spell_name = "ViegoE", root_type = "linear"},
		{spell_name = "ViegoEMissile", root_type = "linear"},
		{spell_name = "ViegoEWallFollowMis", root_type = "linear"},
		{spell_name = "ViegoEWallFollowMisCounterClockwise", root_type = "linear"},
		{spell_name = "ViegoR", root_type = "linear"},
	},
	["Viktor"] = {
		{spell_name = "ViktorChaosStorm", root_type = "circular"},
		{spell_name = "ViktorChaosStormGuide", root_type = "circular"},
		{spell_name = "ViktorGravitonField", root_type = "circular"},
	},
	["Vladimir"] = {
		{spell_name = "VladimirHemoplague", root_type = "circular"},
	},
	["Volibear"] = {
		{spell_name = "VolibearE", root_type = "circular"},
		{spell_name = "VolibearR", root_type = "circular"},
	},
	["Warwick"] = {
		{spell_name = "WarwickR", root_type = "circular"},
	},
	["Xayah"] = {
		{spell_name = "XayahR", root_type = "circular"},
		{spell_name = "XayahQ", root_type = "circular"},
	},
	["Xerath"] = {
		{spell_name = "XerathLocusOfPower2", root_type = "circular"},
		{spell_name = "XerathRMissileWrapper", root_type = "circular"},
		{spell_name = "XerathLocusPulse", root_type = "circular"},
		{spell_name = "XerathArcanopulseChargeUp", root_type = "linear"},
		{spell_name = "XerathArcaneBarrage2", root_type = "circular"},
		{spell_name = "XerathMageSpear", root_type = "circular"},
	},
	["XinZhao"] = {
		{spell_name = "XinZhaoW", root_type = "linear"},
	},
	["Yasuo"] = {
		{spell_name = "YasuoR", root_type = "circular"},
		{spell_name = "YasuoQ1Wrapper", root_type = "circular"},
		{spell_name = "YasuoQ2W", root_type = "circular"},
		{spell_name = "YasuoQ2Wrapper", root_type = "circular"},
		{spell_name = "YasuoQ3Mis", root_type = "circular"},
		{spell_name = "YasuoQ3MisMinion", root_type = "circular"},
		{spell_name = "YasuoQ3W", root_type = "circular"},
		{spell_name = "YasuoQ3Wrapper", root_type = "circular"},
		{spell_name = "YasuoQW", root_type = "circular"},
		{spell_name = "YasuoW", root_type = "circular"},
		{spell_name = "YasuoPassive", root_type = "circular"},
	},
	["Yone"] = {
		{spell_name = "YoneR", root_type = "circular"},
		{spell_name = "YoneQ", root_type = "circular"},
		{spell_name = "YoneQ3", root_type = "circular"},
		{spell_name = "YoneQ3Missile", root_type = "circular"},
		{spell_name = "YoneW", root_type = "circular"},
		{spell_name = "YoneE", root_type = "circular"},
	},
	["Yorick"] = {
		{spell_name = "YorickR", root_type = "circular"},
		{spell_name = "YorickW", root_type = "circular"},
		{spell_name = "YorickE", root_type = "circular"},
	},
	["Yuumi"] = {
		{spell_name = "YuumiQ", root_type = "circular"},
		{spell_name = "YuumiQCast", root_type = "circular"},
		{spell_name = "YuumiQSkillShot", root_type = "linear"},
		{spell_name = "YuumiQSpellPassive", root_type = "circular"},
	},
	["Zac"] = {
		{spell_name = "ZacR", root_type = "circular"},
		{spell_name = "ZacQ", root_type = "circular"},
		{spell_name = "ZacE", root_type = "circular"},
	},
	["Zed"] = {
		{spell_name = "ZedUltMissile", root_type = "circular"},
		{spell_name = "ZedQ", root_type = "circular"},
		{spell_name = "ZedQMissile", root_type = "circular"},
		{spell_name = "ZedShurikenMisOne", root_type = "circular"},
		{spell_name = "ZedShurikenMisThree", root_type = "circular"},
		{spell_name = "ZedShurikenMisTwo", root_type = "circular"},
		{spell_name = "ZedW", root_type = "linear"},
		{spell_name = "ZedShadowDash", root_type = "linear"},
		{spell_name = "ZedShadowDashMissile", root_type = "circular"},
		{spell_name = "ZedWMissile", root_type = "circular"},
	},
	["Zeri"] = {
		{spell_name = "ZeriQ", root_type = "circular"},
		{spell_name = "ZeriQMis", root_type = "circular"},
		{spell_name = "ZeriQMisEmpowered", root_type = "circular"},
		{spell_name = "ZeriQMisEmpoweredParent", root_type = "circular"},
		{spell_name = "ZeriQMisEmpoweredPierce", root_type = "circular"},
		{spell_name = "ZeriQMisEmpoweredPierceParent", root_type = "circular"},
		{spell_name = "ZeriQMisParent", root_type = "circular"},
		{spell_name = "ZeriQMisPierce", root_type = "circular"},
		{spell_name = "ZeriQMisPierceParent", root_type = "circular"},
	},
	["Ziggs"] = {
		{spell_name = "ZiggsQ", root_type = "circular"},
		{spell_name = "ZiggsW", root_type = "circular"},
		{spell_name = "ZiggsE", root_type = "circular"},
		{spell_name = "ZiggsE2", root_type = "circular"},
		{spell_name = "ZiggsR", root_type = "circular"},
		{spell_name = "OdysseyAugments_ZiggsE", root_type = "circular"},
		{spell_name = "OdysseyAugments_ZiggsEMissile", root_type = "circular"},
		{spell_name = "OdysseyAugments_ZiggsESeekers", root_type = "circular"},
		{spell_name = "OdysseyAugments_ZiggsR", root_type = "circular"},
	},
	["Zilean"] = {
		{spell_name = "ZileanQ", root_type = "circular"},
		{spell_name = "ZileanQBuffer", root_type = "circular"},
		{spell_name = "ZileanQGround", root_type = "circular"},
	},
	["Zoe"] = {
		{spell_name = "ZoeQ", root_type = "circular"},
		{spell_name = "ZoeQInterstitial", root_type = "circular"},
		{spell_name = "ZoeQMis2", root_type = "circular"},
		{spell_name = "ZoeQMis2SleepCombo", root_type = "circular"},
		{spell_name = "ZoeQMis2Warning", root_type = "circular"},
		{spell_name = "ZoeQMis2Warning2", root_type = "circular"},
		{spell_name = "ZoeQMis2WarningSleepCombo", root_type = "circular"},
		{spell_name = "ZoeQMissile", root_type = "circular"},
		{spell_name = "ZoeQRecast", root_type = "circular"},
		{spell_name = "ZoeW_SummonerFlash", root_type = "circular"},
		{spell_name = "ZoeE", root_type = "circular"},
		{spell_name = "ZoeEb", root_type = "circular"},
		{spell_name = "ZoeEb2", root_type = "circular"},
		{spell_name = "ZoeEb3", root_type = "circular"},
		{spell_name = "ZoeEb4", root_type = "circular"},
		{spell_name = "ZoeEb5", root_type = "circular"},
		{spell_name = "ZoeEDistanceSolver", root_type = "circular"},
		{spell_name = "ZoeEDistanceSolver2", root_type = "circular"},
		{spell_name = "ZoeEDistanceSolver3", root_type = "circular"},
		{spell_name = "ZoeEDistanceSolver4", root_type = "circular"},
		{spell_name = "ZoeEMis", root_type = "circular"},
		{spell_name = "ZoeEMis2", root_type = "circular"},
		{spell_name = "ZoeEMisAudio", root_type = "circular"},
		{spell_name = "ZoeEv8", root_type = "circular"},
		{spell_name = "ZoeR", root_type = "circular"},
		{spell_name = "ZoeRVFXTrail", root_type = "circular"},
	},
	["Zyra"] = {
		{spell_name = "ZyraQ", root_type = "circular"},
		{spell_name = "ZyraW", root_type = "circular"},
		{spell_name = "ZyraE", root_type = "linear"},
		{spell_name = "ZyraR", root_type = "circular"},
		{spell_name = "ZyraRSplash", root_type = "circular"},
		{spell_name = "ZyraPSeedMis", root_type = "circular"},
	},
}